### ISSUE TITLE
you probably should stop this project

### ISSUE THREAD

**Issue by valina354** [Vortex-Engine/vortex-engine#1]
i was looking through github randomly and i noticed this, this is breaking the source engine sdk eula https://github.com/ValveSoftware/source-sdk-2013/blob/master/LICENSE and will potentially get you sued by valve if you continue this, im not a valve employee nor claim to be but there has been lots of cases recently of valve suing so it could potentially happen and higher chance if someone tries to use this for a commerical game.

**Comment by GuestSneezeOSDev** [comment]
I Will change the license
