### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ThePixelMoon** [Vortex-Engine/vortex-engine#2]
do you have discord i want to talk to you guestsneeze something

**Comment by GuestSneezeOSDev** [comment]
I used to I will make an account

**Comment by GuestSneezeOSDev** [comment]
@xaruc_ in discord

**Comment by ThePixelMoon** [comment]
ok accept my friend request

**Comment by GuestSneezeOSDev** [comment]
@ThePixelMoon I have lost my discord account but you can use my other one @GuestSneezePlayz
