### ISSUE TITLE
bindings for Python 3.

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [Vortex-Engine/vortex-engine#27]
https://github.com/Sandern/py-source-sdk-2013

**Comment by GuestSneezeOSDev** [comment]
this will be in a seperate branch

**Comment by GuestSneezeOSDev** [comment]
`rewrite` branch

**Comment by ThePixelMoon** [comment]
i built that
and that
and that
and that
and that
and that
and that
and that
and that
and that
and that
and that
and that
and that
and that
and that
and that
and that
and that
and that
and that
and that
