### ISSUE TITLE
[bug][csm] CSM is causing issues in Vortex

### ISSUE THREAD

**Issue by maksw2** [Vortex-Engine/vortex-engine#6]
VPC - Valve Project Creator For Visual Studio, Xbox 360, PlayStation 3, Xcode and Make (Build: Aug 27 2014 12:55:48)
(C) Copyright 1996-2010, Valve Corporation, All rights reserved.

Source Path: C:\Users\maksw\Documents\vortex-engine\mp\src
Target Platform: win32
Generating for Visual Studio 2013.

Valid: 'captioncompiler.vcxproj' Passes CRC Checks.

Parsing: client_hl2mp.vpc
ERROR: Bad Syntax in '..\..\game\client\client_base.vpc' line:503

Script Stack:
   ..\..\game\client\client_base.vpc Line:503
   client_hl2mp.vpc Line:11

**Comment by GuestSneezeOSDev** [comment]
I will patch it as soon as possible sorry for the late reply

**Comment by GuestSneezeOSDev** [comment]
Patched please compile your game with the latest version

**Comment by GuestSneezeOSDev** [comment]
if it is still happening Just comment

**Comment by maksw2** [comment]
what csm? it was a broken vpc. i'll check when i can.

**Comment by GuestSneezeOSDev** [comment]
The CSM I developed is specifically tailored for the singleplayer experience and was not designed with multiplayer functionality in mind.

**Comment by maksw2** [comment]
vpc now works fine, so cool.

**Comment by maksw2** [comment]
@GuestSneezeOSDev same thing happens in sp

**Comment by GuestSneezeOSDev** [comment]
In Singleplayer as well I may have to use a different version of CSM

**Comment by maksw2** [comment]
it's NOT csm! it's a vpc syntax error. just move the include elsewhere?

**Comment by GuestSneezeOSDev** [comment]
https://github.com/Vortex-Engine/vortex-engine/pull/11

**Comment by maksw2** [comment]
looks fixed. too bad we don't have csm 
![image](https://github.com/user-attachments/assets/5c8f0379-4211-4b27-8b5c-cc668ffa8a3d)

**Comment by GuestSneezeOSDev** [comment]
@maksw2 I am currently developing a lighting system for vortex it will be released in the near future

**Comment by maksw2** [comment]
if so, that's cool.

**Comment by ThePixelMoon** [comment]
> @maksw2 I am currently developing a lighting system for vortex it will be released in the near future

i fucking bet you're going to use this
https://developer.valvesoftware.com/wiki/Dynamic_RTT_shadow_angles_in_Source_2007

**Comment by maksw2** [comment]
HAHAHA MOON YOU'RE SO FUNNY

**Comment by GuestSneezeOSDev** [comment]
Its based of off it
