### ISSUE TITLE
[Question] VS2022 support?

### ISSUE THREAD

**Issue by maksw2** [Vortex-Engine/vortex-engine#8]
Easier to compile on modern systems.

**Comment by GuestSneezeOSDev** [comment]
I might implement this soon

**Comment by GuestSneezeOSDev** [comment]
I could use https://github.com/Source-SDK-Resources/source-sdk-vs2022 as base

**Comment by maksw2** [comment]
rewrite?

**Comment by GuestSneezeOSDev** [comment]
Most likely I would but I will need a few days to this entirely

**Comment by GuestSneezeOSDev** [comment]
Will be supported in a few days

**Comment by maksw2** [comment]
cool then.

**Comment by GuestSneezeOSDev** [comment]
I will release it for Singleplayer first then for multiplayer

**Comment by GuestSneezeOSDev** [comment]
@maksw2 https://github.com/Vortex-Engine/vortex-engine/commit/a9a96ca0003ad7d53d78fe65188f166e37195808

**Comment by maksw2** [comment]
looks good to me
